version: "3"

services:
  selenium-hub:
    image: selenium/hub:4.18.1-20240227
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_SESSION_TIMEOUT=60

  chrome:
    image: selenium/node-chrome:4.18.1-20240227
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"  # Optional: to access the VNC GUI
